### ISSUE TITLE
Display bonus points for clans and members on current event pages

### ISSUE THREAD

**Issue by benedfit** [avaclancheuk/destiny-clan-warfare#23]
- [x] Update GetClanLeaderboard enpoint to match data structure of GetAllPlayersHistory e.g. `"BonusPoints1":{"ModifierId":8,"BonusPoints":8}`
- [x] Display results in clan leaderboards
- [x] Display top result in clan summary
- [ ] Display results in member leaderboards
- [ ] Display totals in member summary

**Comment by benedfit** [comment]
@mattybeard first point is for you, rest is for me to do

**Comment by mattybeard** [comment]
Added this: http://destinyclanwarfare.azurewebsites.net/api/Leaderboard/GetClanLeaderboardV2?clanId=2107828
Let me know if you drop the usage of the first one and I'll remove it entirely.
