### ISSUE TITLE
Could GameWon be null in GetAllPlayersHistory for PvE activities?

### ISSUE THREAD

**Issue by benedfit** [avaclancheuk/destiny-clan-warfare#24]
This is to disable to green/red highlighting on the current event member pages. 

I think the site would still work if it was null, but I'd need to confirm

**Comment by benedfit** [comment]
v1.2.2 will handle `gameWon` so that it can be `true`, `false`, or `null`

**Comment by mattybeard** [comment]
Gonna catch up on these today but trying to work out your context for this - are you asking me does my code make it possible to be null? No, it cannot - it would always default to false.
