### ISSUE TITLE
Feature request: Visibility of clan/player platform

### ISSUE THREAD

**Issue by benedfit** [avaclancheuk/destiny-clan-warfare#70]
`maybe a platform logo listed with clans on the leaderboard to know what platform the competition is playing on and/or platform-specific leaderboards`

**Comment by benedfit** [comment]
@mattybeard how easy would this be? How do we deal with people who are in more than on clan across different platforms?

**Comment by mattybeard** [comment]
A clan can be multi platform can't it? I store at Clan Member level what console they are in but not at clan level.

**Comment by benedfit** [comment]
ok, so if you could surface that flag for me, I could determine what to show for the clan based on whether they have a mix of people from many platforms or just one

**Comment by mattybeard** [comment]
GetAllMembers?

**Comment by mattybeard** [comment]
Added.
Xbox: 1
Psn: 2
Blizzard: 4
